version: '3.5'
services:
  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME}_mariadb
    networks:
      - backend
    restart: always
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--max-connections=512'
      - '--innodb-buffer-pool-size=256M'
      - '--innodb-log-buffer-size=32M'
      - '--innodb-file-per-table=1'
    ports:
      - '${MYSQL_EXPOSE_PORT}:3306'
    volumes:
      - './database:/var/lib/mysql'
    logging:
      driver: json-file
      options: { max-size: '200k', max-file: '1' }
  wordpress:
    image: wordpress:5-fpm
    container_name: ${APP_NAME}_wordpress
    networks:
      - frontend
      - backend
    restart: always
    environment:
      - TZ=${TZ}
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WORDPRESS_STORAGE}:/var/www/html
    logging:
      driver: json-file
      options: { max-size: '200k', max-file: '1' }
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    networks:
      - frontend
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - '${NGINX_EXPORT_HTTP_PORT}:80'
      - '${NGINX_EXPORT_HTTPS_PORT}:443'
    volumes:
      - ./certs:/opt/certs:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${WORDPRESS_STORAGE}:/var/www/html:ro
    logging:
      driver: json-file
      options: { max-size: '200k', max-file: '1' }

networks:
  frontend:
    name: ${APP_NAME}_frontend
  backend:
    name: ${APP_NAME}_backend
